# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(592, 409)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_outermost = QtWidgets.QFrame(Form)
        self.frame_outermost.setStyleSheet("#frame_outermost{\n"
"border-top: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"border-radius: 5px;\n"
"}")
        self.frame_outermost.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_outermost.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_outermost.setObjectName("frame_outermost")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_outermost)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_strategy_name = QtWidgets.QLabel(self.frame_outermost)
        self.label_strategy_name.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_strategy_name.setObjectName("label_strategy_name")
        self.verticalLayout_5.addWidget(self.label_strategy_name)
        self.frame = QtWidgets.QFrame(self.frame_outermost)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.comboBox_symb_name = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_symb_name.setObjectName("comboBox_symb_name")
        self.verticalLayout_3.addWidget(self.comboBox_symb_name)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBox_atm_option = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_atm_option.setObjectName("comboBox_atm_option")
        self.verticalLayout_2.addWidget(self.comboBox_atm_option)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.comboBox_expiry_date = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_expiry_date.setObjectName("comboBox_expiry_date")
        self.verticalLayout_4.addWidget(self.comboBox_expiry_date)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_generate_graph = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_generate_graph.setObjectName("pushButton_generate_graph")
        self.gridLayout_2.addWidget(self.pushButton_generate_graph, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout_5.addWidget(self.frame)
        self.gridLayout.addWidget(self.frame_outermost, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_strategy_name.setText(_translate("Form", "{Strategy Name}"))
        self.label.setText(_translate("Form", "Symbol Name"))
        self.label_2.setText(_translate("Form", "Strike option"))
        self.label_3.setText(_translate("Form", "Expiry Date"))
        self.pushButton_generate_graph.setText(_translate("Form", "Generate Graph"))
